### ISSUE TITLE
建议与思考

### ISSUE THREAD

**Issue by dcy10000** [happy-js/vue-happy-bus#1]
这个方案可能不适合非父子的组件的通信。
因为BusFactory(this)只能设置一个vue组件，在这个组件销毁时调用$off。这意味这个 bus 只能在当前组件中调用$on,否则行为将不符合期望。
可能每次调用的时候指定当前 组件更合适
`this.bus.$on(this,eventName,callback);`

**Comment by tangdaohai** [comment]
@dcy10000 首先谢谢提出建议。

此方案定位是为了解决在多组件通信时使用 vue bus 造成的额外书写成本。

`this.bus.$on(this,eventName,callback)` 对于这种使用方式，在前期设计时也考虑过，后来是想通过 vue.use 注入到原型中。但这种方式对项目侵入较大，故而放弃了。

不过当前这种写法耦合度较低。
